import { Footer } from '@/presentation/components/layouts/Footer';
import styles from './Auth.module.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div style={{ backgroundColor: 'blue' }} className={styles.error }>
      {children}

      <Footer />
    </div>
  );
}
