export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function ApplicationsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div style={{ backgroundColor: 'blue' }}>{children}</div>;
}
